### PR TITLE
add version control

### PR DESCRIPTION
**Pull request by SpudGunMan**
add git commit value as a tracking token on the deployable files

### CODE REVIEW

**Review by ste7anste7an — COMMENTED** [review]
Could you please describe what the result would be of your changes? What I can tell from it, is that the filename of the written install_uartremote.py would contain the commit number. My thought was, that the install script would always be in sync with the latest commit (because that triggers the Action) and there would be no need for a commit number, because there is only one single version of the nstall_uartremote.py script present.

**Comment by SpudGunMan** [comment]
I forgot about the automation in GitHub install_uartremote.py would have a fingerprint for tracking as well as the addition of a debug version return ... with lots of bricks to manage this was an attempt at getting details from the lib directly. I fixed it so it is now just failing on the OS call which may be fixable with the automation system .. should I try to fix it? or just keep changes local for now?

**Comment by SpudGunMan** [comment]
I fixed the automation component for building SPIKE

**Comment by SpudGunMan** [comment]
dont pull this yet I did find a problem in the cloud

**Comment by SpudGunMan** [comment]
got this working correctly now

**Review by ste7anste7an — COMMENTED** [review]
It would be nice to have the version method also available in uartremote.py used for the other platforms, and not only for the uartremote library build by the create_install_file.py.
We could do something like the following in the Action script:

add this to uartremote.py:

```
    def get_version(self):
        git_version='3e44072'
        if self.DEBUG:print(git_version)
        return git_version
```
This shell script replaces the current commit_id in uartremote.py by the newly commited one and pushes uartremote.py. This shell script can be part of an Action.

```
COMMIT_ID=`git rev-parse --short HEAD`
sed -i "s/git_version='[0-9a-fA-F]*'/git_version='$COMMIT_ID'/g" uartremote.py

git add uartremote.py
git commit -m "updated commit version $COMMIT_ID"
git push
```

Only problem is that by pushing this new version, the commit id will become yet a new one. But at least, for all platforms the `get_version()` method is up to date.

**Comment by SpudGunMan** [comment]
updated version function - yes git commit isn't the best for version tracking but without a compiler of traditional sense keeping version control on a .py file is difficult, its really just so dont need to think hard to check if all uartremote versions are the same build version or not - - I was just quickly trying to solve the issue when I dont know which brick has what code on it

I was thinking this might also be handy to check and alert if your peer is running a different version and would cause issues
```
    def get_version(self):
        git_version='{version}'
        if self.DEBUG:print(git_version)
        return git_version
```

**Comment by SpudGunMan** [comment]
rather then git we could also just use a build date and time stamp

**Review by ste7anste7an — COMMENTED** [review]
Why don't we just hard code the version in uartremote.py. We add 

```
    def get_version(self):
        version='2022021900'
        if self.DEBUG:print(version)
        return version
```

Every time we update uartremote.py , we take the new date. For the same date we increase the counter 2022021900 --> 2022021901, etc.

I know, it is not automated, but works for all platforms and gives a meaningful version number. Do you agree?

**Comment by SpudGunMan** [comment]
for sure, I will just close this - I am just horrible at remembering to update haha ;)

**Pull request closed without merging**
